-- =============================================================================
-- V1 — Estrutura inicial: usuários, perfis de acesso, sessões e trilha de auditoria.
--
-- Convenções adotadas em todo o schema (Seção 7 da especificação):
--   * nomes em snake_case; PKs `bigint generated always as identity`;
--   * enums de domínio como VARCHAR + CHECK, para evoluir sem lock de tabela;
--   * exclusão lógica via `deleted_at`, com unicidade parcial que a respeita;
--   * instantes sempre em `timestamptz` (RN-22); a exibição em America/Recife
--     é responsabilidade da camada de apresentação;
--   * toda FK tem índice.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- usuario — quem acessa o sistema. Um perfil por usuário (RN-19).
-- -----------------------------------------------------------------------------
CREATE TABLE usuario (
    id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome             varchar(160) NOT NULL,
    email            varchar(180) NOT NULL,
    senha_hash       varchar(120) NOT NULL,
    perfil           varchar(20)  NOT NULL,
    ativo            boolean      NOT NULL DEFAULT true,
    ultimo_acesso_em timestamptz,
    created_at       timestamptz  NOT NULL,
    created_by       varchar(180) NOT NULL,
    updated_at       timestamptz  NOT NULL,
    updated_by       varchar(180) NOT NULL,
    deleted_at       timestamptz,
    CONSTRAINT ck_usuario_perfil CHECK (perfil IN ('ADMIN', 'GESTOR_FROTA', 'CONSULTA')),
    CONSTRAINT ck_usuario_nome_nao_vazio CHECK (length(btrim(nome)) > 0),
    CONSTRAINT ck_usuario_email_minusculo CHECK (email = lower(email))
);

COMMENT ON TABLE  usuario IS 'Usuários do sistema. Exclusão é sempre lógica (deleted_at).';
COMMENT ON COLUMN usuario.perfil IS 'ADMIN | GESTOR_FROTA | CONSULTA (RN-19).';
COMMENT ON COLUMN usuario.senha_hash IS 'Hash com prefixo de algoritmo, ex.: {bcrypt}$2a$...';

-- Unicidade de e-mail apenas entre usuários vivos: um e-mail liberado por exclusão
-- lógica pode ser reaproveitado, sem colidir com o histórico.
CREATE UNIQUE INDEX ux_usuario_email_ativo ON usuario (email) WHERE deleted_at IS NULL;
CREATE INDEX ix_usuario_perfil ON usuario (perfil) WHERE deleted_at IS NULL;

-- -----------------------------------------------------------------------------
-- sessao_refresh — um registro por refresh token emitido.
-- Existe para tornar o token revogável: sem isto, o logout não teria efeito real
-- até a expiração natural do token.
-- -----------------------------------------------------------------------------
CREATE TABLE sessao_refresh (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario_id  bigint      NOT NULL REFERENCES usuario (id),
    jti         uuid        NOT NULL UNIQUE,
    expira_em   timestamptz NOT NULL,
    revogado_em timestamptz,
    criado_em   timestamptz NOT NULL,
    user_agent  varchar(400),
    endereco_ip varchar(60)
);

COMMENT ON TABLE  sessao_refresh IS 'Sessões de refresh token. Artefato técnico, expurgado após a expiração.';
COMMENT ON COLUMN sessao_refresh.jti IS 'Identificador único do token, conferido a cada renovação.';

CREATE INDEX ix_sessao_refresh_usuario ON sessao_refresh (usuario_id);
CREATE INDEX ix_sessao_refresh_expira_em ON sessao_refresh (expira_em);

-- -----------------------------------------------------------------------------
-- revisao_auditoria — cabeçalho de revisão do Hibernate Envers, estendido com o
-- autor e o identificador da requisição. Responde "quem mudou o quê e quando"
-- (Seção 3.5 e RN-18).
-- -----------------------------------------------------------------------------
CREATE TABLE revisao_auditoria (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revisado_em bigint       NOT NULL,
    usuario     varchar(180) NOT NULL,
    request_id  varchar(64)
);

COMMENT ON TABLE  revisao_auditoria IS 'Revisões do Envers. `revisado_em` é epoch em milissegundos, formato do Envers.';

CREATE INDEX ix_revisao_auditoria_revisado_em ON revisao_auditoria (revisado_em);

-- -----------------------------------------------------------------------------
-- usuario_aud — histórico de alterações de usuário.
-- `senha_hash` e `ultimo_acesso_em` ficam fora da trilha: o primeiro por ser
-- segredo, o segundo por ser ruído operacional que inflaria o histórico.
-- -----------------------------------------------------------------------------
CREATE TABLE usuario_aud (
    id         bigint   NOT NULL,
    rev        bigint   NOT NULL REFERENCES revisao_auditoria (id),
    revtype    smallint NOT NULL,
    nome       varchar(160),
    email      varchar(180),
    perfil     varchar(20),
    ativo      boolean,
    created_at timestamptz,
    created_by varchar(180),
    updated_at timestamptz,
    updated_by varchar(180),
    deleted_at timestamptz,
    PRIMARY KEY (id, rev)
);

COMMENT ON TABLE  usuario_aud IS 'Trilha do Envers para usuario. revtype: 0=inserção, 1=alteração, 2=exclusão.';

CREATE INDEX ix_usuario_aud_rev ON usuario_aud (rev);
